name: Delete Old Releases

on:
  workflow_call:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Delete all releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching all releases..."
          releases=$(gh release list --limit 100 --json tagName --jq '.[].tagName')

          if [ -z "$releases" ]; then
            echo "No releases found."
            exit 0
          fi

          for release in $releases; do
            echo "Deleting release: $release"
            gh release delete "$release" -y
          done
