name: Delete Old Releases

on:
  workflow_call:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Delete old releases (keep latest)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching all releases..."
          releases=$(gh release list --limit 100 --json tagName,createdAt --jq 'sort_by(.createdAt) | reverse | .[].tagName')

          if [ -z "$releases" ]; then
            echo "No releases found."
            exit 0
          fi

          # Convert the list of releases into an array
          readarray -t release_array <<< "$releases"

          echo "Keeping the latest release: ${release_array[0]}"

          for ((i=1; i<${#release_array[@]}; i++)); do
            release="${release_array[$i]}"
            echo "Deleting release: $release"
            gh release delete "$release" -y
          done
